"""
Django settings for Ecommerce project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t+c+h-hj8@1a4c8e##pnordkg(pfj$#a15q&b14px=8&zi)@$_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Ecommerce.app1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecommerce.Ecommerce.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

import os
WSGI_APPLICATION = 'Ecommerce.Ecommerce.wsgi.application'

# Database
# Prefer explicit MySQL env vars on Render, otherwise parse DATABASE_URL
from django.core.exceptions import ImproperlyConfigured
DATABASES = {}
if os.environ.get("RENDER"):
    mysql_host = os.environ.get("MYSQLHOST")
    mysql_name = os.environ.get("MYSQLDATABASE")
    mysql_user = os.environ.get("MYSQLUSER")
    mysql_password = os.environ.get("MYSQLPASSWORD")
    mysql_port = os.environ.get("MYSQLPORT") or "3306"
    if mysql_host and mysql_name and mysql_user is not None:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": mysql_name,
                "USER": mysql_user,
                "PASSWORD": mysql_password,
                "HOST": mysql_host,
                "PORT": mysql_port,
            }
        }
    elif os.environ.get("DATABASE_URL"):
        # Use dj-database-url if DATABASE_URL is provided
        try:
            import dj_database_url

            DATABASES["default"] = dj_database_url.parse(os.environ.get("DATABASE_URL"))
        except Exception as e:
            raise ImproperlyConfigured("DATABASE_URL set but dj-database-url not available: %s" % e)
    else:
        # Fall back to sqlite on Render if no DB env vars provided
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEBUG = True

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RAZORPAY_KEY_ID = 'rzp_test_gmNV6d0IgHC0g8'
RAZORPAY_KEY_SECRET = 'WYpmrAjgeRPzLGZuZpqAyH8b'

WSGI_APPLICATION = 'Ecommerce.wsgi.application'

# RAZORPAY_KEY_ID = 'rzp_test_5Z0zF57atG3j8t'
# RAZORPAY_KEY_SECRET = '92ASZcqvQcILG5HBwuYMLhz7'